Repository netbox-community/netbox, pull requests merged in 2024-08, with the labels that each got.

#17101 17086 Fix exception on job details view
  netbox/templates/core/job.html
Labels: beta

#17162 Fixes #17098: Prevent automatic deletion of related notifications when deleting an object
  netbox/netbox/models/features.py
Labels: beta

#17164 Closes #17143: Deprecate the use of dedicated nested API serializers
  netbox/circuits/api/nested_serializers.py
  netbox/circuits/api/serializers.py
  netbox/circuits/api/serializers_/nested.py
  netbox/circuits/api/serializers_/providers.py
  netbox/core/api/nested_serializers.py
  netbox/core/api/serializers.py
  netbox/dcim/api/nested_serializers.py
  netbox/dcim/api/serializers.py
  netbox/dcim/api/serializers_/device_components.py
  netbox/dcim/api/serializers_/devices.py
  netbox/dcim/api/serializers_/devicetype_components.py
  netbox/dcim/api/serializers_/nested.py
  netbox/dcim/api/serializers_/sites.py
  netbox/dcim/api/serializers_/virtualchassis.py
  netbox/extras/api/nested_serializers.py
  netbox/extras/api/serializers.py
  netbox/ipam/api/nested_serializers.py
  netbox/ipam/api/serializers.py
  netbox/ipam/api/serializers_/ip.py
  netbox/ipam/api/serializers_/nested.py
  netbox/netbox/api/serializers/nested.py
  netbox/tenancy/api/nested_serializers.py
  netbox/tenancy/api/serializers.py
  netbox/tenancy/api/serializers_/contacts.py
  netbox/tenancy/api/serializers_/nested.py
  netbox/tenancy/api/serializers_/tenants.py
  netbox/users/api/nested_serializers.py
  netbox/users/api/serializers.py
  netbox/users/api/serializers_/nested.py
  netbox/users/api/serializers_/permissions.py
  netbox/virtualization/api/nested_serializers.py
  netbox/virtualization/api/serializers.py
  netbox/virtualization/api/serializers_/nested.py
  netbox/virtualization/api/serializers_/virtualmachines.py
  netbox/vpn/api/nested_serializers.py
  netbox/vpn/api/serializers.py
  netbox/wireless/api/nested_serializers.py
  netbox/wireless/api/serializers.py
  netbox/wireless/api/serializers_/nested.py
  netbox/wireless/api/serializers_/wirelesslans.py
Labels: beta

#17171 17159 fix plugin install instructions
  netbox/templates/core/inc/plugin_installation.html
Labels: beta

#17176 17163 Fix services list on IPAddress view
  netbox/templates/ipam/ipaddress.html
Labels: beta

#17172 17169 use config_name for matching in plugin catalog
  netbox/core/plugins.py
  netbox/core/tables/plugins.py
  netbox/templates/core/plugin.html
Labels: beta

#17180 Closes #16574: Add last_synced time to REST API serializer for data sources
  netbox/core/api/serializers_/data.py
Labels: beta

#17161 Fixes #17097: Record static object representation when calling `NotificationGroup.notify()`
  netbox/extras/events.py
  netbox/extras/views.py
  netbox/templates/htmx/notifications.html
Labels: beta

#17178 Closes #17173: Update GraphQL web front end dependencies
  netbox/project-static/dist/graphiql/graphiql.min.css
  netbox/project-static/dist/graphiql/graphiql.min.js
  netbox/project-static/dist/graphiql/index.umd.js
  netbox/project-static/dist/graphiql/plugin-explorer-style.css
  netbox/project-static/netbox-graphiql/package.json
  netbox/project-static/yarn.lock
Labels: beta

#17194 17193 update logo in Readme
  docs/netbox_logo.png
  docs/netbox_logo.svg
  netbox/project-static/img/netbox.ico
  netbox/project-static/img/netbox_logo.svg
  netbox/project-static/img/netbox_touch-icon-180.png
Labels: beta

#17192 17174 add version to plugin catalog
  netbox/core/plugins.py
  netbox/core/tables/plugins.py
Labels: beta

#17232 Fixes: 17177 - Add "facility" field to LocationFilterForm
  netbox/dcim/forms/filtersets.py
Labels: type: feature

#17233 Fixes: #17072 - Make active links of phone and email in Contact Assignments table
  netbox/tenancy/tables/contacts.py
Labels: type: feature

#17234 Fixes: #17070 - Make image_width and image_height read_only on REST API ImageAttachmentSerializer
  netbox/extras/api/serializers_/attachments.py
Labels: type: feature

#17235 Fixes: #16949 - Device count column on Sites table
  netbox/dcim/tables/sites.py
  netbox/dcim/views.py
Labels: type: feature

#17241 Closes #17221: Extend ObjectEditView to support HTMX requests
  netbox/netbox/views/generic/object_views.py
Labels: beta

#17237 Add styling to rendered-markdown class to clamp height and add scrollbar
  netbox/project-static/dist/netbox.css
  netbox/project-static/styles/custom/_markdown.scss
Labels: type: feature

#17267 Fixes: #17108 - Update isotime and isodate filters to be timezone-aware
  netbox/extras/forms/reports.py
  netbox/extras/forms/scripts.py
  netbox/utilities/templatetags/builtins/filters.py
Labels: type: bug
